add create a phoneix app to intro curriculum and add thank you credit
elixir-bridge/elixir-bridge.github.io pull request #23
Opened 2016-09-25 00:22 UTC by aneyzberg

2016-09-25 00:45 UTC, photomattmills commented on installfest/general-elixirbridge-info.markdown
> +The ElixirBridge curriculum is heavily based on the [Intro to Rails Curriculum](http://docs.railsbridge.org/intro-to-rails/), minus the the parts of the curriculum that are Elixir and Phoenix specifi
`allowed us ElixirBridge` should maybe be `allowed ElixirBridge`

2016-09-25 00:45 UTC, photomattmills reviewed
one minor copyedit, otherwise looks good.

2016-09-27 04:48 UTC, mkb requested changes

2016-09-27 04:48 UTC, mkb commented on installfest/general-elixirbridge-info.markdown
> +[Installfest](installfest/01-begin-installfest.html)
I'm guessing these links will break since they're relative. Whack everything up to and including the slash and they should work fine.

2016-09-27 04:48 UTC, mkb commented on suggestotron/02-getting-started.markdown
> +[Creating a New App](suggestotron/03-create-a-phoenix-app.html)
Same thing here. I'm guessing these two will break.

2016-09-27 05:35 UTC, aneyzberg commented on installfest/general-elixirbridge-info.markdown
> +[Installfest](installfest/01-begin-installfest.html)
sounds good. I was just following your example in the other sections.

2016-09-28 05:29 UTC, aneyzberg commented
links are fixed. Is there are bug in github. The changes have been addressed but the comments are not disappearing?

2016-09-28 17:18 UTC, mkb commented
@aneyzberg Good question. Maybe they just changed the behavior? No idea.

2016-09-28 19:34 UTC, photomattmills commented
@aneyzberg @mkb they changed the behavior with the new code review feature.

2016-09-29 04:47 UTC, aneyzberg commented
so is this good to go @photomattmills @auser @mkb

2016-09-29 21:59 UTC, photomattmills commented
@aneyzberg should be fine

2016-09-29 21:59 UTC, merged